server:
  port: 11000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  elasticsearch:
    rest:
      uris: 192.168.200.123:9200
      connection-timeout: 1s
      read-timeout: 30s
logging:
  level:
    tracer: trace
    com.gmall.search: trace
