server:
  port: 10000


spring:
  autoconfigure:
    #屏蔽数据源配置
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:
    host: 192.168.200.123
    port: 6379
    password: 123456